#!/usr/bin/env bash
# =============================================================================
#  Local -> server — daily deploy
# =============================================================================
#
#  Step loop run after every code change:
#    1. rsync local code to /opt/pocket-claude (except data/, .env, .venv)
#    2. If requirements.txt changed: pip install in the server venv
#    3. systemctl restart pocket-claude
#    4. /health check via the public tunnel URL
#
#  Requirements — set up once on the server host:
#    - Your user is a member of the `pocket-claude` group (can write to
#      /opt/pocket-claude)
#    - NOPASSWD sudo for `systemctl * pocket-claude` (no password prompt)
#    - NOPASSWD sudo for `-u pocket-claude .../pip` (needed only when
#      requirements.txt changed — see step 2)
#
#  Configuration via env vars (e.g. in ~/.zshrc):
#      export POCKET_CLAUDE_TARGET="your-user@minipc"
#      export POCKET_CLAUDE_PUBLIC_URL="https://my-host.tailnet-name.ts.net"
#
#  Usage (in the local repo root):
#      ./deploy/push-to-minipc.sh
#  or double-click "Update Mini-PC.command".
# =============================================================================
set -euo pipefail

# Defaults from env, otherwise error out if nothing is configured.
TARGET="${POCKET_CLAUDE_TARGET:-${TARGET:-}}"
REMOTE_PATH="${REMOTE_PATH:-/opt/pocket-claude}"
PUBLIC_URL="${POCKET_CLAUDE_PUBLIC_URL:-${PUBLIC_URL:-}}"

if [[ -z "$TARGET" ]] || [[ -z "$PUBLIC_URL" ]]; then
    cat >&2 <<EOF
Error: configuration missing. Set once in ~/.zshrc:
    export POCKET_CLAUDE_TARGET="<user>@<host>"           # e.g. your-user@minipc.local
    export POCKET_CLAUDE_PUBLIC_URL="https://<fqdn>"      # e.g. https://my-host.tailnet.ts.net

Then open a new shell and re-run the script.
EOF
    exit 1
fi

c_blue()   { printf '\033[1;34m%s\033[0m\n' "$*"; }
c_green()  { printf '\033[1;32m%s\033[0m\n' "$*"; }
c_yellow() { printf '\033[1;33m%s\033[0m\n' "$*"; }
c_red()    { printf '\033[1;31m%s\033[0m\n' "$*" >&2; }
step()     { echo; c_blue "==> $*"; }

LOCAL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$LOCAL_DIR"

step "Code -> $TARGET:$REMOTE_PATH"

# First: did requirements.txt change?
REMOTE_REQ_HASH="$(ssh -o BatchMode=yes "$TARGET" \
    "sha256sum $REMOTE_PATH/requirements.txt 2>/dev/null | cut -d' ' -f1" || echo "")"
LOCAL_REQ_HASH="$(shasum -a 256 requirements.txt | cut -d' ' -f1)"

# rsync with explicit excludes:
#   data/        -> SQLite + uploads stay server-side (database authority!)
#   .env         -> server has its own .env with its own SERVER_TOKEN
#   .venv        -> Python binaries are platform-specific (macOS != Linux)
#   .git/        -> we don't need git history on the server
#   __pycache__/ -> regenerated by the server Python
#   *.pyc        -> same as above
#   .DS_Store    -> macOS junk
rsync -az --delete \
    --exclude='.venv' \
    --exclude='data' \
    --exclude='.env' \
    --exclude='.git' \
    --exclude='__pycache__' \
    --exclude='*.pyc' \
    --exclude='.DS_Store' \
    --exclude='Pocket Claude Server.command' \
    --exclude='Update Dependencies.command' \
    ./ "$TARGET:$REMOTE_PATH/" 2>&1 | tail -3

c_green "    Code in sync."

# If requirements.txt changed: pip install in the server venv
if [[ "$LOCAL_REQ_HASH" != "$REMOTE_REQ_HASH" ]]; then
    step "requirements.txt changed -> pip install in the server venv"
    ssh "$TARGET" "sudo -n -u pocket-claude $REMOTE_PATH/.venv/bin/pip install --quiet --upgrade -r $REMOTE_PATH/requirements.txt" 2>&1 | head -10
    c_green "    Dependencies updated."
fi

step "systemctl restart pocket-claude"
ssh "$TARGET" 'sudo -n systemctl restart pocket-claude'
sleep 2

step "Health check via public URL"
if curl -fsS --max-time 8 "$PUBLIC_URL/health" >/dev/null 2>&1; then
    HEALTH="$(curl -fsS "$PUBLIC_URL/health")"
    c_green "    ✓ $PUBLIC_URL -> $HEALTH"
else
    c_red "    ! Health endpoint does not respond!"
    echo "       Logs (last 20 lines):"
    ssh "$TARGET" 'sudo -n journalctl -u pocket-claude -n 20 --no-pager' | sed 's/^/         /'
    exit 1
fi

echo
c_green "Deploy finished — server is running the current code."
echo
